[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "json_extract"
version = "0.1.0"
authors = [
  { name="Vatsa", email="228140210+svr-s@users.noreply.github.com" },
]
description = "A robust JSON-to-CSV extraction engine for deeply nested payloads."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pandas>=1.0.0"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.setuptools.packages.find]
where = ["src"]

[project.urls]
Homepage = "https://github.com/svr-s/json_extract"
Issues = "https://github.com/svr-s/json_extract/issues"